### ISSUE TITLE
unicode representations

### ISSUE THREAD

**Issue by ololoe** [Drekin/win-unicode-console#22]
It's not directly connected to your project, but is there a way to make repr() return unicode rather then \uXXXX escapes?

**Comment by Drekin** [comment]
Note that this is problem only under Python 2. Under Python 3, `repr` returns a Unicode string and the escapes occurs only when sys.stdout.encoding cannot handle the string, and it happens in `sys.displayhook`. On the other hand under Python 2, `repr` has to return bytes str by definition so there is no way to get the actual Unicode string.

**Comment by ololoe** [comment]
>Under Python 3, repr returns a Unicode string and the escaping occurs only when sys.stdout.encoding cannot handle the string, and it happens in sys.displayhook.

Thanks, never knew it. If I would like to change it, where should it be fixed? In __repr__ of every object, or is there a better way?

**Comment by Drekin** [comment]
So you are in the Python 2 case? I don't know what to do here, you cannot get the “original” unicode repr, you just get a sequence of bytes some of which may or may not be escapes of the original unicode characters. For your custom objects, you could implement `__unicode_repr__` and your own displayhook that uses this attribute when present and that specialcases `unicode` objects. Or the displayhook may try to detect escape sequences and translate them back to original characters. It depends on reprs of which objects you are interested.
