### ISSUE TITLE
Unable to print kanji or other asian language characters

### ISSUE THREAD

**Issue by abhimanyuPathania** [Drekin/win-unicode-console#28]
Using `win-unicode-console` removed the exceptions raised by python when printing Unicode to cmd-prompt. But I noticed that cmd-prompt is unable to display characters from languages like Japanese, Mandarin or Korean. It is able to display most European languages. I tried printing German, Italian, Greek, French, Hungarian, Spanish etc and they all worked. My code looked like this:

```python
# -*- coding: UTF-8 -*-

from __future__ import unicode_literals
import win_unicode_console

win_unicode_console.enable()

print('光り射す場所へ')
```
I tried it on Python 2.7.11 and Python 3.5.1 on  Windows7 (all are 64 bit) with cmd-prompt set to `Consolas` font.
Is this an encoding problem with `win-unicode-console` or a limitation of font?

**Comment by anthrotype** [comment]
It's likely a limitation of the font:
http://superuser.com/a/584598

**Comment by Drekin** [comment]
Yes, it's a limitation of the font. I assume you are getting just boxes or something like that, but there is a correct number of them, and if you are able to enter those characters, you are getting the correct data in Python (even thought you cannot display the characters).

**Comment by abhimanyuPathania** [comment]
Yes I do see boxes. But in my original script, I am also writing Unicode to a file after explicitly encoding it in `UTF-8`. Then when I open that text file with [Notepad2](http://www.flos-freeware.ch/notepad2.html) (since original notepad won't display `UTF-8` ), I am able to see the content correctly. And Notepad2 is using the `Consolas` font by default. 
So the font seems to be capable or there should be something more to it.
(_I was going to edit my original comment to include this information but replies came before that_ )...

**Comment by anthrotype** [comment]
Your text editor must be using some other font as a fallback.

**Comment by Drekin** [comment]
According to https://www.microsoft.com/typography/fonts/font.aspx?FMID=1924 and http://www.fileformat.info/info/unicode/font/consolas/list.htm, Consolas supports Latin, Greek and Cyrillic, but not Asian scripts.

**Comment by abhimanyuPathania** [comment]
Yes. That does seem to be the case. The same true for the other supported font, [Lucida Console](https://www.microsoft.com/typography/fonts/family.aspx?FID=18).

It would be nice to include this information somewhere in documentation. Since this package is exclusively made for windows users to support Unicode from console and there doesn't seem any straightforward way to write all of Unicode to console due to fonts that are allowed.

_Should I close the issue?_

**Comment by Drekin** [comment]
`win-unicode-console` fixes the problem in communication between Python and the standard Windows console. Now you *can* write Unicode to console. The fact that the console itself cannot display the characters that are not present in the used font is a different issue and is not directly connected to Python. Actually there is a note in the documentation, that you of course need a font that contains the characters you want to display. Maybe the information can be extended, but it is not easy to find a suitable font. For example I use DejaVu Sans Mono – it doesn't support Asian scripts but contains some mathematical symbols I use (but still not all of them).

If you find a suitable font for your use case, I'll be happy if you share your experience here. For now I'm closing the issue.
