### ISSUE TITLE
 EOFError() when using raw_input() on certain input in Windows

### ISSUE THREAD

**Issue by Nandaka** [Drekin/win-unicode-console#41]
Hi,

I'm using Windows and Python 2.7. with win_unicode_console 0.5

Some input will raise EOFError, when other doesn't.

Sample code
```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

import win_unicode_console
win_unicode_console.enable()

try:
    input = raw_input('input?')

    print input
except:
    print sys.exc_info()
```

Sample Input
- `多々良小傘` = raise EOFError
- `たたらこがさ` = OK

**Comment by Drekin** [comment]
This is a pretty stupid bug. At the lowest level, the EOF was tested as a byte rather than as a Windows wide char. This causes EOF whenever the lower byte of the first character is b'\x1a', which is the case for your first input. It should be fixed now, try the latest development version.

**Comment by Nandaka** [comment]
Looks like it is working.

Thanks
