### ISSUE TITLE
Module unnecessary?

### ISSUE THREAD

**Issue by ololoe** [Drekin/win-unicode-console#45]
Python 3.8 well handles unicode input/output to console by itself. Unicode command line parameters were in 3.x from the beginning. The only thing you need now is to set stdout/stderr encoding for the case they will be redirected. So it there a reason to use win-unicode-console?

**Comment by ololoe** [comment]
Some funny stuff.

Python throws an exception without `sys.stdout.reconfigure(encoding='utf-8')` when redirecting stdout, but works fine with stderr.

**Comment by Drekin** [comment]
I think unicode is handled already since Python 3.6, so win-unicode-console is not needed. Only if someone wants Unicode console in older 3.x or 2.7.

**Comment by ololoe** [comment]
You should place a warning in readme then.

**Comment by Drekin** [comment]
Ok, done.

**Comment by ololoe** [comment]
Would you update this too? https://pypi.org/project/win_unicode_console/

**Comment by Drekin** [comment]
It seems I cannot just add info there, I would need to make a new release just to make a comment that the package is actually not needed…

**Comment by ololoe** [comment]
Then do it.
